name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  checkes:
    name: Checks
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        sudo apt-get install libgl1-mesa-dev
        go get -v -t -d ./...

    # - name: Build
    #   run: go build -v ./...

    - name: Test
      run: go test -v -flags headless ./...
    
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v1.2.1
      with:
        version: v1.30.0
        args: --build-tags headless
