name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v1.2.1
      with:
        version: v1.30
        args: --build-tags headless

    - name: Get dependencies
      run: go get -tags headless -v -t -d ./...

    - name: Build
      run: go build -tags headless -v ./...

    - name: Test
      run: go test -tags headless -v ./...
